### ISSUE TITLE
RIPEMD160 issue

### ISSUE THREAD

**Issue by madtocc** [jerson/openpgp-mobile#12]
@jerson hey! 

I'm trying to encrypt a message using the flutter package and I'm getting an error due the hash used. The error is due the GO library not directly related to your package... I think some ppl will eventually face this issue as well tho.

The error is:
openpgp: invalid argument: cannot encrypt because no candidate hash functions are compiled in. (Wanted RIPEMD160 in this case.)

I did a little research and apparently golang.org/x/crypto/openpgp package is frozen and deprecated. It is suggested to use a fork instead [github.com/ProtonMail/go-crypto](https://github.com/ProtonMail/go-crypto).
I have tried here directly in GO using the fork and I am able to encrypt the message. Is it possible to replace golang.org/x/crypto/openpgp package with the ProtonMail fork i.e github.com/ProtonMail/go-crypto/openpgp package?

Thanks

**Comment by jerson** [comment]
hey @madtocc thanks for report the issue i think that this is the fix for that

```go
import (
	// this is a temporary fix to add missing crypto
	_ "golang.org/x/crypto/ripemd160"
)
```

**Comment by madtocc** [comment]
Thanks for the prompt reply :)
I saw the _ "golang.org/x/crypto/ripemd160" but I don't know if it actually fixes it, apparently not...

There's an info here https://github.com/golang/go/issues/44226 regarding the frozen/deprecated x/crypto/openpgp. They suggest ProtonMail fork as an alternative and since it is backwards compatible with x/crypto/openpgp it shouldn't bring any issues (hopefully 😅)

**Comment by jerson** [comment]
Thanks, im gonna replace and run some test to make sure that everything works as expected. i will let you know when is updated

**Comment by madtocc** [comment]
Thanks, sure lmk I'll be happy to test here as well.

**Comment by jerson** [comment]
hey i just release a new version with this commit https://github.com/jerson/openpgp-mobile/commit/943f2088c4b51afe2158ba4964c13a57fbac10bb
https://github.com/jerson/openpgp-mobile/releases/tag/v1.2.0

there is a small diference in size (left: before, right: after)
![image](https://user-images.githubusercontent.com/325780/135553982-a563ea3d-2e7f-4f2b-bd51-5bd4097355da.png)

but i think is acceptable, can you please help me to test
thanks.

**Comment by madtocc** [comment]
@jerson sure mate, I will give a go later today and will provide feedback. 
Thanks!

**Comment by jerson** [comment]
hey @madtocc thanks for that.

https://pub.dev/packages/openpgp/versions/3.1.0

version 3.1.0 was released 

for now im gonna close this issue but feel free to reopen if you want

have a great day.
