### ISSUE TITLE
dynamic lib support

### ISSUE THREAD

**Issue by joe-getcouragenow** [jerson/openpgp-mobile#3]
This is highly relevant to your work with allowing flutter and golang to be nice with each other.

https://github.com/jpnurmi/dart_dylib/blob/master/lib/dylib.dart

Uses an advanced FFI branch: https://github.com/jpnurmi/ffigen/tree/nested-structs

**Comment by jerson** [comment]
hi @joe-getcouragenow  thanks for that, now im using ffi but for mac im still using .a , but yeah that would be a good aproach :D

**Comment by jerson** [comment]
good news :D dylib support added to macos in 

https://github.com/jerson/flutter-openpgp/commit/fe777ec6bfef6768413e018df78ba1f5d9a285b3

**Comment by joe-getcouragenow** [comment]
@jerson thank you for letting us know.

this is really useful for our own project as we were hitting similar problems
