### ISSUE TITLE
Tinygo with protobufs not working..

### ISSUE THREAD

**Issue by gedw99** [jerson/openpgp-mobile#4]
https://github.com/tinygo-org/tinygo/releases/tag/v0.17.0

Worth trying again

wasmer also hit v1 last week too for running server side .

https://wasmer.io/posts/wasmer-go-embedding-1.0

**Comment by jerson** [comment]
Hi @gedw99 thanks for share this info, this weekend im gonna try latest versions, wish me luck 😁

**Comment by gedw99** [comment]
Hey @jerson awesome 

You might be interested in https://github.com/genjidb/genji
Its a SQL DB and a KV DB based on Badger, and runs on Web, Desktop, Server and mobile.
It might be good for your project because it can encrypt the data at rest against whatever keys (openpgp or rsa )  you choose and also rotate te keys within the browser, mobile, desktop or server.
Kind of MongoDB and SQLite rolled into one. I have been using it for a few months and its usable.


Just a few days ago the developer tried the latest tinygo, and bam boom it works !!

see: https://github.com/genjidb/genji.js/blob/master/package.json#L22. The yarn script calls the .sh script that calls tinygo.

Here is a makefile to do it all.
just do ``` make all ```, and it will pull the code and compile it.  The output WASM file will be in **genji.js/dist**

makefile:
````



all: g-dep js-dep js-dep-os g-all js-build

all-delete: g-dep-delete js-dep-delete

# https://github.com/genjidb/genji

LIB_NAME=genji
LIB=github.com/genjidb/$(LIB_NAME)


g-dep:
	git clone https://$(LIB)
g-dep-delete:
	rm -rf $(LIB_NAME)

g-init:
	cd $(LIB_NAME) && go mod tidy
g-all:
	cd $(LIB_NAME) && $(MAKE) all
g-gen:
	cd $(LIB_NAME) && $(MAKE) gen
g-build:
	cd $(LIB_NAME) && $(MAKE) build
g-test:	
	cd $(LIB_NAME) && $(MAKE) test
g-bench:
	cd $(LIB_NAME) && $(MAKE) bench
g-run:
	genji -h

#### JS / WASM

# https://github.com/genjidb/genji.js

JS_LIB_NAME=genji.js
JS_LIB=github.com/genjidb/$(JS_LIB_NAME)


js-dep:
	git clone https://$(JS_LIB)
js-dep-delete:
	rm -rf $(JS_LIB_NAME)

js-dep-os:
	# tinygo
	brew tap tinygo-org/tools
	brew install tinygo
	tinygo version

js-build:
	# also calls tinygo.
	cd $(JS_LIB_NAME) && yarn install && yarn build


````

**Comment by jerson** [comment]
Wow thas awesome, im gonna take a look on that, im still having some issues with protobuf and tinygo, so probable i need to research a bit more in order to have an initial working build

**Comment by gedw99** [comment]
ok. Happy to have a look at stuff if you want a second opinion, etc

**Comment by jerson** [comment]
yeah sure that would be nice, main code is in wasm dir, main dep is protobuf

**Comment by jerson** [comment]
Hey im working on a branch with flatbuffers instead of protobuf and seems like tinygo works :D , still needs some changes in order to release a new version but its a good progress

https://github.com/jerson/openpgp-mobile/tree/flatbuffers

**Comment by gedw99** [comment]
Ok will take a look.

Yeah i am also starting to use flat buffers more and more.
Mostly because of Arrow.

**Comment by gedw99** [comment]
you might be interested in this then btw:
this flutter project uses flatbuffers is a really interesting way: https://github.com/wuba/fair
they take dart code and then compile it into a bin vm format using flat buffers.
then at run time, you can load flutter code dynamically on a mobile ( for example ).

Am playing around with it currently to see how viable it is for loading GUI dynamcially.

**Comment by 1l0** [comment]
@jerson Thanks for your god's work. I'm really interested in the outcome of Flutter <- Flatbuffers -> Go frontend stack.

**Comment by jerson** [comment]
Thanks @1l0 i have some progress in flutter library https://github.com/jerson/flutter-openpgp/tree/flatbuffers but im a bit blocked by null safety implementation of flatbuffers in dart https://github.com/google/flatbuffers/issues/6282 

and in the mid time im working on react native library version with JSI (c++ instead of classic bridge) 
https://github.com/jerson/react-native-fast-openpgp/tree/flatbuffers

hopefully next weeks i will have more progress on it

**Comment by gedw99** [comment]
ok

**Comment by gedw99** [comment]
I am not using the flatbuffers branch currently, but instead the master branch.

I just tried getting tinygo to work.


## Reproduction.

makefile extended with tinygo

```

.PHONY: wasm
wasm:
	mkdir -p output/wasm
	cd wasm && GOARCH=wasm GOOS=js go build -ldflags="-s -w" -o ../output/wasm/openpgp.wasm main.go
	cp $(GOROOT)/misc/wasm/wasm_exec.js  output/wasm/wasm_exec.js
	cp output/wasm/openpgp.wasm wasm/sample/public/openpgp.wasm
	cp output/wasm/wasm_exec.js  wasm/sample/public/wasm_exec.js
wasm-tinygo:
	mkdir -p output/wasm
	#cd wasm && GOARCH=wasm GOOS=js go build -ldflags="-s -w" -o ../output/wasm/openpgp.wasm main.go
	cd wasm && tinygo build -o ../output/wasm/openpgp.wasm -target wasm --no-debug main.go

```

output:
```
openpgp-mobile git:(master) ✗ make wasm-tinygo
mkdir -p output/wasm
#cd wasm && GOARCH=wasm GOOS=js go build -ldflags="-s -w" -o ../output/wasm/openpgp.wasm main.go
cd wasm && tinygo build -o ../output/wasm/openpgp.wasm -target wasm --no-debug main.go
# encoding/json
/usr/local/opt/go/libexec/src/encoding/json/decode.go:160:15: cannot convert nil (untyped nil value) to reflect.Type
/usr/local/opt/go/libexec/src/encoding/json/decode.go:232:26: cannot use nil (untyped nil value) as reflect.Type value in assignment
/usr/local/opt/go/libexec/src/encoding/json/decode.go:249:30: cannot convert nil (untyped nil value) to reflect.Type
/usr/local/opt/go/libexec/src/encoding/json/decode.go:515:8: v.NumMethod undefined (type reflect.Value has no field or method NumMethod)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:552:7: v.SetLen undefined (type reflect.Value has no field or method SetLen)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:589:6: v.SetLen undefined (type reflect.Value has no field or method SetLen)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:620:40: v.NumMethod undefined (type reflect.Value has no field or method NumMethod)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:921:9: v.NumMethod undefined (type reflect.Value has no field or method NumMethod)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:950:6: v.SetBytes undefined (type reflect.Value has no field or method SetBytes)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:957:9: v.NumMethod undefined (type reflect.Value has no field or method NumMethod)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:990:9: v.NumMethod undefined (type reflect.Value has no field or method NumMethod)
/usr/local/opt/go/libexec/src/encoding/json/decode.go:1014:23: v.OverflowFloat undefined (type reflect.Value has no field or method OverflowFloat)
make: *** [wasm-tinygo] Error 1

```

## Possible approach to fix

There are 2 libs being used for json marshal and unmarshal without reflection. they are also faster.

https://github.com/buger/jsonparser

here is an example of it being used: https://github.com/genjidb/genji/blob/c36c9500d9cde6801d49879abbc1da77fa6c9854/document/value.go#L506

---

This one generates the  json marshal and unmarshal, which is nicer.
https://github.com/moznion/go-json-ice




i think the fix is to use a different json lib like the one that genji uses

**Comment by jerson** [comment]
thanks for share this info, i tried replace jsonparser and after replace all references there are more issues related about encoding, all related to protobuf, thats why im removing protobuf with flatbuffers

**Comment by gedw99** [comment]
Ok makes sense.

looks like flutter buffers is the better way to architect this.

I am using this architecture for a few projects but can probably change over to flat buffers without too much refactoring .

Let me know if we should close this …
